config/routes.rb
CleanIt::Application.routes.draw do
  devise_for :users, :path_names => { :sign_up => "randomunguessablename" }

  get 'user' => "users#show", :path => "customer/dashboard"

  get 'new_booking' => "bookings#new", :path => "cleaning"

  get 'check_email' => "users#check_email_uniqueness", :path => "/check_email_uniqueness"

  get 'about' => "about#index"

  post 'bookings' => "bookings#create"

  post 'twilio' => "twilio#send_text_message"

  root 'home#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base

  belongs_to :worker
  belongs_to :user
 
  has_many :booking_jobs
  has_many :jobs, :through => :booking_jobs  

  def calculate_price(hours)
    price = hours * HOURLY_PRICE + SUPPLIES_PRICE
    convert_price_to_stripe(price)
  end

  def convert_price_to_stripe(price)
    price * 100
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :set_prices

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create        
    @booking = Booking.new(booking_params)

    @booking.price = @booking.calculate_price(params[:booking][:hours].to_i)
    @booking.save

    create_booking_job_instances_from_array(save_jobs, @booking)
    
    if user_signed_in? 
      @user = User.find(current_user.id)
      @booking.user = @user
      Mailer.new_booking(@user, @booking).deliver
    else
      @user = @booking.build_user(user_params[:user])
      # stripe_user_object = User.create_stripe_user(params[:stripeToken], @user.name)
      # @user.stripe_id = stripe_user_object.id
      @user.password = Devise.friendly_token.first(8)
      @user.save
      Mailer.welcome(@user, @booking).deliver
    end

    # CHARGE THE CARD
    # begin
      # charge = Stripe::Charge.create(
      #   :amount => @booking.price, # amount in cents, again
      #   :currency => "usd",
      #   :customer => @user.stripe_id,
      # )

    # rescue Stripe::CardError => e
    #   # The card has been declined
    # end

    respond_to do |format|
      if @booking.save
        sign_in(:user, @user)
        format.html { redirect_to user_url, notice: 'Booking was saved! Check your email for confirmation.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:time, :needs_supplies, :hours, :price)
    end

    def booking_job_params
      params.require(:booking).permit(job: [:bedroom, :bathroom, :extras])
    end

    def user_params
      binding.pry
      params.require(:booking).permit(user: [:name, :address, :city, :state, :zipcode, :email, :phone])
    end

    def create_booking_job_instances_from_array(array, booking)
      array.each do |element|
        @booking_job = booking.booking_jobs.create
        job = Job.find_by name: element
        @booking_job.job_id = job.id
        @booking_job.booking_id = booking.id
        @booking_job.save
      end
    end

    def set_prices
      gon.price = HOURLY_PRICE
      gon.supplies_price = SUPPLIES_PRICE
    end

    def save_jobs
      jobs = booking_job_params[:job][:extras].split(",")
      jobs << booking_job_params[:job][:bedroom]
      jobs << booking_job_params[:job][:bathroom]
    end

end

app/helpers/bookings_helper.rb
module BookingsHelper
  def supply_price
    SUPPLIES_PRICE
  end
end

app/views/bookings/_contact_info.html.erb
<div id="contact-info" style="display:none;">
    <div id="error_field"></div>
    <div>
    <%= f.fields_for :user do |builder| %> 
      <div class="header">
        <h1>Contact Info</h1>
      </div>

        <div class="house-details form-group-field">
          <div class="header">
              <h4>Name</h4>
          </div>
          <%= builder.text_field :name, :as => :user["name"], :id => "name_input", :placeholder => "Full name", :class => "contact-info-item", :required => true, :tabindex => 1, :autofocus => true,
           :value => current_user_value("name") %><br />
        </div>

        <div class="house-details form-group-field">
          <div class="header cleaning_address">
            <h4>Cleaning Address</h4>
          </div>

            <div class="address_fields">
            <%= builder.text_field :address, :as => :user["address"], :id => "street_address", :placeholder => "Street address", :class => "contact-info-item", :required => true, :tabindex => 2, :value => current_user_value("address") %><br />

              <div id="the_state" class="address_field">
                <%= builder.text_field :state, :as => :user["state"], :id => "state", :placeholder => "State", :class => "contact-info-item", :required => true, :tabindex => 4, :value => current_user_value("state") %><br />
              </div>

              <div id="the_city" class="address_field">
                <%= builder.text_field :city, :as => :user["city"], :id => "city", :placeholder => "City", :class => "contact-info-item", :required => true, :tabindex => 3, :value => current_user_value("city") %><br /> 
              </div>

              <div id="the_zipcode" class="address_field">
                <%= builder.text_field :zipcode, :as => :user["zipcode"], :id => "zipcode", :placeholder => "Zipcode", :class => "contact-info-item", :required => true, :tabindex => 5, :value => current_user_value("zipcode") %><br />
              </div>
            </div>

        </div>    

        <br>
          <div id="test">
        </div>

        <div class="header">
          <h5>We'll only contact you about your cleaning, promise :)</h5>
        </div>

        <div class="house-details form-group-field">
          <div class="header">
            <h4>Email</h4>
          </div>
          <%= builder.text_field :email, :as => :user["email"], :id => "email_input", :placeholder => "Email address", :class => "contact-info-item", :required => true, :tabindex => 6, :value => current_user_value("email") %><br />
        </div>

        <div class="house-details form-group-field">
          <div class="header">
            <h4>Phone</h4>
          </div>
          <%= builder.text_field :phone, :as => :user["phone"], :id => "phone_input", :placeholder => "(xxx) xxx-xxxx", :class => "contact-info-item", :required => true, :tabindex => 7, :value => current_user_value("phone") %><br />
        </div>


        <%= link_to "Next", '#schedule-time', :id => "contact-info-complete", :class => "btn btn-success btn-block", :tabindex => 8 %>

    <% end %>  
    </div> 

    <!-- tracking pixel -->
    <%= image_tag "contact-info.png" %>
  </div>

app/views/bookings/_credit_cards.html.erb
<div class="card-assurance" style="display:none;" >You won't be charged until the day of the cleaning, and you'll get a receipt immediately by email.
    </div>
    <%= image_tag "discover_64.png", :class => "card-icon", :style => "margin-top:25px; margin-left:10px;"%>
    <%= image_tag "american_express_64.png", :class => "card-icon", :style => "margin-top:25px; margin-left:0px;"%>
    <%= image_tag "mastercard_gold_64.png", :class => "card-icon", :style => "margin-top:25px; margin-left:0px;"%>
    <%= image_tag "visa_64.png", :class => "card-icon", :style => "margin-top:25px; margin-left:0px;"%>
    <%= image_tag "stripe.png", :class => "card-icon", :style => "margin-top:15px; margin-left:10px;"%>

app/views/bookings/_customer_cleaning.html.erb
<div id="booking-details" style="display:block;">
    <div class="header">
      <h1>Customize Your Cleaning</h1>
    </div>

        <div class="btn-group btn-group-lg house-details rooms">
            <div class="header">
              <h4>Bedrooms</h4>
            </div>

          <input type="hidden" id="bedroom-value" value="1 bedroom" name="booking[job][bedroom]"/>
          <div class="form-group-field btn-group bedroom roomcount">
            <button type="button" class="btn btn-success btn-number" onclick='setBedroomValue("1 bedroom")'>1</button>
            <button type="button" class="btn btn-number" onclick='setBedroomValue("2 bedrooms")'>2</button>
            <button type="button" class="btn btn-number" onclick='setBedroomValue("3 bedrooms")'>3</button>
            <button type="button" class="btn btn-number" onclick='setBedroomValue("4 bedrooms")'>4</button>
            <button type="button" class="btn btn-number" onclick='setBedroomValue("5+ bedrooms")'>5+</button>
          </div>
        </div>

      <div class="btn-group btn-group-lg house-details rooms">
          <div class="header">
            <h4>Bathrooms</h4>
          </div>

        <input type="hidden" id="bathroom-value" value="1 bathroom" name="booking[job][bathroom]"/>
        <div class="form-group-field btn-group">
          <button type="button" class="btn btn-success btn-number" onclick='setBathroomValue("1 bathroom")'>1</button>
          <button type="button" class="btn btn-number" onclick='setBathroomValue("2 bathrooms")'>2</button>
          <button type="button" class="btn btn-number" onclick='setBathroomValue("3+ bathrooms")'>3+</button>
        </div>
      </div>

      <div class="btn-group btn-group-lg house-details" id="extras">
          <div class="header extras">
            <h4>Extras</h4>
          </div>
        <div id="house-extras">

          <input type="hidden" id="extras-value" value="" name="booking[job][extras]"/>
          <div class="form-group-field btn-group extras">
            <button type="button" class="btn" id="fridge-button" onclick='setExtrasValue("Fridge")'>Fridge</button>
            <button type="button" class="btn" id="oven-button" onclick='setExtrasValue("Oven")'>Oven</button>
            <button type="button" class="btn" id="cabinets-button" onclick='setExtrasValue("Inside Cabinets")'>Inside Cabinets</button>
          </div>
          <div class="form-group-field btn-group extras">
            <button type="button" class="btn interior" id="windows-button" onclick='setExtrasValue("Interior Windows")'>Interior Windows</button>
            <button type="button" class="btn interior" id="walls-button" onclick='setExtrasValue("Interior Walls")'>Interior Walls</button>
          </div>
        </div>
      </div>

    <div class="house-details btn-group hours">  
      <div class="header">
        <h4>Number of hours to Book (2 minimum)</h4>
        <h6 style="margin-left:10px;" id="recommended_hours_label">We recommend <strong><span id="recommended_hours">2</span></strong> hours based on the size of your place.</h6>
      </div>
      <div id="hour-dropdown">
        <%= f.select :hours, ( (2..13).step(0.5).map{|n| n%1 == 0 ? n.to_i : n} ), :as => :booking["hours"] %>
        <h6 style="float:right; margin:0 35px 0 0; font-weight:400;">$<%= HOURLY_PRICE %>/hour</h6>
      </div>

    </div>



      <%= link_to "Next", '#contact-info' , :id => "booking-details-complete", :class => "btn btn-success btn-block" %>

      <!-- tracking pixel -->
    <%= image_tag "customize-cleaning.png" %>
  </div>

app/views/bookings/_finalize_booking.html.erb
<div id="finalize-booking" style="display:none;">

  <div class="header">
      <h1>Review order</h1>
  </div>
 <%= f.submit "Book cleaning", :class => "btn btn-success btn-block", :id => "finalize-booking-button" %>
  <div class="confirmations-details">
    <div class="confirmation">
        <h3 id="confirmation-time"></h3>
      <div class="time-container">
        <h4 id="confirmation-hours"></h4>
        <h4 id="booking-price" class="details"></h4>
        <h4 id="confirmation-supplies">Supplies cost:</h4>
        <h4 id="supply-cost" class="details">Free</h4>
        <hr style="margin:0, margin-bottom:10px;">
        <h4 id="confirmation-total">Total:</h4>
        <h4 id="confirmation-amount"></h4>
      </div>
    </div>

    <div class="confirmation">
      <h2 class="confirmation-header">Cleaning Info</h2>      

      <div class="house-confirmation">
        <h3 id="confirmation-bedrooms" class="room-confirmation"></h3>
        <h3 id="confirmation-bathrooms" class="room-confirmation"></h3>
        <h4 id="confirmation-extras"></h4>

        <hr style="margin:0;">

        <h5 id="confirmation-address" class="address-confirmation"></h5>
        <h5 id="confirmation-city-state-zip" class="address-confirmation"></h5>
      </div>

      
    </div>

    <div class="confirmation">
      <h2 class="confirmation-header">Your Info</h2>
      <h3 id="confirmation-name"  class="confirmation-contact-info"></h3>
      <h3 id="confirmation-email" class="confirmation-contact-info"></h3>
      <h3 id="confirmation-phone" class="confirmation-contact-info"></h3>
    </div>
  </div>



    <%= f.submit "Book cleaning", :class => "btn btn-success btn-block", :id => "finalize-booking-button" %>

    <!-- tracking pixel -->
    <%= image_tag "finalize-booking.png" %>
  </div>

app/views/bookings/_form.html.erb
<%= form_for @booking, :authenticity_token => true, :html => { :id => "cleaning-form" } do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  

  <%= render 'progress_bar' %>

  <%= render 'customer_cleaning', :f => f %>

  <%= render 'contact_info', :f => f %>

  <%= render 'schedule_time', :f => f %>

  <%= render 'payment_info', :f => f %>

  <%= render 'finalize_booking', :f => f %>

<% end %>

app/views/bookings/_payment_info.html.erb
<div id="payment-info" style="display:none;">
    <div class="header">
      <h1>Payment info</h1>
    </div>

    <div class="house-details form-group-field">
      <div class="header">
        <h4>Credit Card Number</h4>
      </div>
      <%= text_field_tag :card_number, nil, :class => "valid payment-form", name: nil, :placeholder => "Card Number", :data => {:stripe => 'number' }, :tabindex => 1, :autofocus => true %>
      <%= image_tag "lock.png" %>
    </div>

    <div class="house-details form-group-field">
      <div class="header">
        <h4>Card security code (CVC)</h4>
      </div>
      <%= text_field_tag :card_code, nil,:class => "valid payment-form" , name: nil, :placeholder => "3 or 4 digits", :data => {:stripe => 'cvc' }, :tabindex => 2 %>
    </div>

    <div class="house-details form-group-field">
      <div class="header expiration_date">
        <h4>Expiration date</h4>
      </div>
      <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month", :data => {:stripe => 'exp-month' } } %>
      <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year", :data => {:stripe => 'exp-year' } } %>
    </div>

      <%= link_to "Next", '#finalize-booking', :id => "payment-info-complete", :class => "btn next-step btn-block", :tabindex => 3 %>

      <!-- tracking pixel -->
    <%= image_tag "payment-info.png" %>
  </div>

app/views/bookings/_progress_bar.html.erb
<div class="progress-bar" style="margin-left:0px;">
    <p class="progress-bar-item" id="progress-bar-item-one">1</p>
    <p class="progress-bar-item" id="progress-bar-item-two">2</p>
    <p class="progress-bar-item" id="progress-bar-item-three">3</p>
    <p class="progress-bar-item" id="progress-bar-item-four">4</p>
    <p class="progress-bar-item" id="progress-bar-item-five">5</p>
</div>

<div></div>

<hr>

app/views/bookings/_schedule_time.html.erb
<div id="schedule-time" style="display:block;">
    <div class="header">
      <h1>Schedule a time</h1>
    </div>

    <div id="calendar"></div>

    <hr>
    
    <input type="hidden" id="reservation-time" value="" name="booking[time]"/>

    <div id="calendar-days" class="calendar-buttons">
        <button type="button" class="btn time" value="10.00">7:30 AM</button>
        <button type="button" class="btn time" value="10.00">9:00 AM</button>
        <button type="button" class="btn time" value="10.00">10:00 AM</button>
        <button type="button" class="btn time" value="10.30">10:30 AM</button>
        <button type="button" class="btn time" value="11.00">11:00 AM</button>
        <button type="button" class="btn time" value="11.30">11:30 AM</button>
        <button type="button" class="btn time" value="12.00">12:00 PM</button>
        <button type="button" class="btn time" value="13.00">1:00 PM</button>
        <button type="button" class="btn time" value="13.30">1:30 PM</button>
        <button type="button" class="btn time" value="14.00">2:00 PM</button>
        <button type="button" class="btn time" value="15.00">3:00 PM</button>
        <button type="button" class="btn time" value="16.00">4:00 PM</button>
        <button type="button" class="btn time" value="16.30">4:30 PM</button>
        <button type="button" class="btn time" value="17.00">5:00 PM</button>
        <button type="button" class="btn time" value="18.00">6:00 PM</button>
        <button type="button" class="btn time" value="18.30">6:30 PM</button>
    </div>

    <%= link_to "Next", '#payment-info', :id => "schedule-time-complete", :class => "btn next-step btn-block" %>

    <!-- tracking pixel -->
    <%= image_tag "schedule-time.png" %>
</div>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Listing bookings</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row" style="">
    <div class="span3"></div>
    <div class="span6 bordered" style="width:460px;">
          <%= render 'form' %>
    </div>

    <div class="span3">

    </div>
    
    <%= render 'credit_cards' %>
  
  </div>
  <p style="text-align:center; font-size: 12px; font-weight: lighter; margin-top:5px;">Every Home a Haven</p>
</div>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>