config/routes.rb
CleanIt::Application.routes.draw do
  devise_for :users, :path_names => { :sign_up => "randomunguessablename" }

  get 'user' => "users#show", :path => "customer/dashboard"

  get 'new_booking' => "bookings#new", :path => "cleaning"

  get 'check_email' => "users#check_email_uniqueness", :path => "/check_email_uniqueness"

  get 'about' => "about#index"

  post 'bookings' => "bookings#create"

  post 'twilio' => "twilio#send_text_message"

  root 'home#index'

end

app/views/layouts/_crazy_egg.html.erb
<script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName("script")[0];
a.src=document.location.protocol+"//dnn506yrbagrg.cloudfront.net/pages/scripts/0015/5438.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>

app/views/layouts/_footer.html.erb
<!-- Start Footer -->

  <div id="footer">
    <div class="f-left">
      &copy; EverHaven - Every Home a Haven
    </div>
    <div class="f-right">
      <%= happy_day %>
    </div>
  </div>

<!-- End Footer -->

app/views/layouts/_footer_images.html.erb
<div id="bottom-4">
    <ul>
      <li><%= image_tag "clean-house-5.jpg" %></li>
      <li><%= image_tag "clean-house-2.jpg" %></li>
      <li><%= image_tag "clean-house-7.jpg" %></li>
      <li><%= image_tag "clean-house-4.jpg" %></li>
    </ul>
</div>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= GOOGLE_ANALYTICS_TRACKING_ID %>', 'everhavenhq.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">

        <title>EverHaven</title>
        <meta name="description" content="">
        <meta name="author" content="">

       <!-- Include GOOGLE Webfonts -->

       <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
        
        <%= stylesheet_link_tag    "application", media: "all" %>
        <%= javascript_include_tag "application" %>
        <%= javascript_include_tag "https://js.stripe.com/v2/" %>
        <%= csrf_meta_tags %>

        <script type="text/javascript">
            Stripe.setPublishableKey('<%= STRIPE_PUBLIC_KEY %>');
        </script>

        <%= include_gon %>   
    </head>

app/views/layouts/_navbar.html.erb
<!-- Start Navbar -->

   <div id="header" class="clearfix">
    <div class="trcontainer">
      <h3><a href="<%= root_url %>" id="brand">EverHaven</a></h3>
      <!-- <h5>Serving Utah, Idaho, and New Mexico</h5> -->
      <ul>
          <li><%= PHONE_NUMBER %> &nbsp;&nbsp;–</li>
          <li><%= link_to "Home", root_url %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Your cleanings', user_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path  %></li>
        <% end %>
          <li><%= link_to 'Book a cleaning', new_booking_path %></li>
          <li><%= link_to 'About us', about_path %></li>
      </ul>
    </div>
  </div>

<!-- End Navbar -->

app/views/layouts/application.html.erb
<%= render "layouts/header" %>
<%= render "layouts/navbar" %>

<body>
  
<!-- devise stuff -->
<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>
<!-- end devise stuff -->

<%= yield %>

<%= render 'layouts/crazy_egg' %>
</body>

<%= render "layouts/google_analytics" %>
</html>